version: '3'
services:
  ###posgres database for inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

###mysql database for inventory
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3307
    expose:
      - 3307

###postgre database for inventory
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
